INSERT INTO brand (name, created_date, created_by, modified_date, modified_by) VALUES ('A', NOW(), 'system', NOW(), 'system');
INSERT INTO brand (name, created_date, created_by, modified_date, modified_by) VALUES ('B', NOW(), 'system', NOW(), 'system');
INSERT INTO brand (name, created_date, created_by, modified_date, modified_by) VALUES ('C', NOW(), 'system', NOW(), 'system');
INSERT INTO brand (name, created_date, created_by, modified_date, modified_by) VALUES ('D', NOW(), 'system', NOW(), 'system');
INSERT INTO brand (name, created_date, created_by, modified_date, modified_by) VALUES ('E', NOW(), 'system', NOW(), 'system');
INSERT INTO brand (name, created_date, created_by, modified_date, modified_by) VALUES ('F', NOW(), 'system', NOW(), 'system');
INSERT INTO brand (name, created_date, created_by, modified_date, modified_by) VALUES ('G', NOW(), 'system', NOW(), 'system');
INSERT INTO brand (name, created_date, created_by, modified_date, modified_by) VALUES ('H', NOW(), 'system', NOW(), 'system');
INSERT INTO brand (name, created_date, created_by, modified_date, modified_by) VALUES ('I', NOW(), 'system', NOW(), 'system');


INSERT INTO category (name, created_date, created_by, modified_date, modified_by) VALUES ('상의', NOW(), 'system', NOW(), 'system');
INSERT INTO category (name, created_date, created_by, modified_date, modified_by) VALUES ('아우터', NOW(), 'system', NOW(), 'system');
INSERT INTO category (name, created_date, created_by, modified_date, modified_by) VALUES ('바지', NOW(), 'system', NOW(), 'system');
INSERT INTO category (name, created_date, created_by, modified_date, modified_by) VALUES ('스니커즈', NOW(), 'system', NOW(), 'system');
INSERT INTO category (name, created_date, created_by, modified_date, modified_by) VALUES ('가방', NOW(), 'system', NOW(), 'system');
INSERT INTO category (name, created_date, created_by, modified_date, modified_by) VALUES ('모자', NOW(), 'system', NOW(), 'system');
INSERT INTO category (name, created_date, created_by, modified_date, modified_by) VALUES ('양말', NOW(), 'system', NOW(), 'system');
INSERT INTO category (name, created_date, created_by, modified_date, modified_by) VALUES ('액세서리', NOW(), 'system', NOW(), 'system');


INSERT INTO product (name, price, brand_id, category_id, status, created_date, created_by, modified_date, modified_by) VALUES ('상의 A', 11200, (SELECT id FROM brand WHERE name = 'A'), (SELECT id FROM category WHERE name = '상의'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('아우터 A', 5500, (SELECT id FROM brand WHERE name = 'A'), (SELECT id FROM category WHERE name = '아우터'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('바지 A', 4200, (SELECT id FROM brand WHERE name = 'A'), (SELECT id FROM category WHERE name = '바지'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('스니커즈 A', 9000, (SELECT id FROM brand WHERE name = 'A'), (SELECT id FROM category WHERE name = '스니커즈'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('가방 A', 2000, (SELECT id FROM brand WHERE name = 'A'), (SELECT id FROM category WHERE name = '가방'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('모자 A', 1700, (SELECT id FROM brand WHERE name = 'A'), (SELECT id FROM category WHERE name = '모자'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('양말 A', 1800, (SELECT id FROM brand WHERE name = 'A'), (SELECT id FROM category WHERE name = '양말'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('액세서리 A', 2300, (SELECT id FROM brand WHERE name = 'A'), (SELECT id FROM category WHERE name = '액세서리'), 'ON_SALE', NOW(), 'system', NOW(), 'system');
INSERT INTO product (name, price, brand_id, category_id, status, created_date, created_by, modified_date, modified_by) VALUES ('상의 B', 10500, (SELECT id FROM brand WHERE name = 'B'), (SELECT id FROM category WHERE name = '상의'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('아우터 B', 5900, (SELECT id FROM brand WHERE name = 'B'), (SELECT id FROM category WHERE name = '아우터'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('바지 B', 3800, (SELECT id FROM brand WHERE name = 'B'), (SELECT id FROM category WHERE name = '바지'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('스니커즈 B', 9100, (SELECT id FROM brand WHERE name = 'B'), (SELECT id FROM category WHERE name = '스니커즈'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('가방 B', 2100, (SELECT id FROM brand WHERE name = 'B'), (SELECT id FROM category WHERE name = '가방'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('모자 B', 2000, (SELECT id FROM brand WHERE name = 'B'), (SELECT id FROM category WHERE name = '모자'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('양말 B', 2000, (SELECT id FROM brand WHERE name = 'B'), (SELECT id FROM category WHERE name = '양말'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('액세서리 B', 2200, (SELECT id FROM brand WHERE name = 'B'), (SELECT id FROM category WHERE name = '액세서리'), 'ON_SALE', NOW(), 'system', NOW(), 'system');
INSERT INTO product (name, price, brand_id, category_id, status, created_date, created_by, modified_date, modified_by) VALUES ('상의 C', 10000, (SELECT id FROM brand WHERE name = 'C'), (SELECT id FROM category WHERE name = '상의'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('아우터 C', 6200, (SELECT id FROM brand WHERE name = 'C'), (SELECT id FROM category WHERE name = '아우터'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('바지 C', 3300, (SELECT id FROM brand WHERE name = 'C'), (SELECT id FROM category WHERE name = '바지'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('스니커즈 C', 9200, (SELECT id FROM brand WHERE name = 'C'), (SELECT id FROM category WHERE name = '스니커즈'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('가방 C', 2200, (SELECT id FROM brand WHERE name = 'C'), (SELECT id FROM category WHERE name = '가방'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('모자 C', 1900, (SELECT id FROM brand WHERE name = 'C'), (SELECT id FROM category WHERE name = '모자'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('양말 C', 2200, (SELECT id FROM brand WHERE name = 'C'), (SELECT id FROM category WHERE name = '양말'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('액세서리 C', 2100, (SELECT id FROM brand WHERE name = 'C'), (SELECT id FROM category WHERE name = '액세서리'), 'ON_SALE', NOW(), 'system', NOW(), 'system');
INSERT INTO product (name, price, brand_id, category_id, status, created_date, created_by, modified_date, modified_by) VALUES ('상의 D', 10100, (SELECT id FROM brand WHERE name = 'D'), (SELECT id FROM category WHERE name = '상의'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('아우터 D', 5100, (SELECT id FROM brand WHERE name = 'D'), (SELECT id FROM category WHERE name = '아우터'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('바지 D', 3000, (SELECT id FROM brand WHERE name = 'D'), (SELECT id FROM category WHERE name = '바지'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('스니커즈 D', 9500, (SELECT id FROM brand WHERE name = 'D'), (SELECT id FROM category WHERE name = '스니커즈'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('가방 D', 2500, (SELECT id FROM brand WHERE name = 'D'), (SELECT id FROM category WHERE name = '가방'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('모자 D', 1500, (SELECT id FROM brand WHERE name = 'D'), (SELECT id FROM category WHERE name = '모자'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('양말 D', 2400, (SELECT id FROM brand WHERE name = 'D'), (SELECT id FROM category WHERE name = '양말'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('액세서리 D', 2000, (SELECT id FROM brand WHERE name = 'D'), (SELECT id FROM category WHERE name = '액세서리'), 'ON_SALE', NOW(), 'system', NOW(), 'system');
INSERT INTO product (name, price, brand_id, category_id, status, created_date, created_by, modified_date, modified_by) VALUES ('상의 E', 10700, (SELECT id FROM brand WHERE name = 'E'), (SELECT id FROM category WHERE name = '상의'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('아우터 E', 5000, (SELECT id FROM brand WHERE name = 'E'), (SELECT id FROM category WHERE name = '아우터'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('바지 E', 3800, (SELECT id FROM brand WHERE name = 'E'), (SELECT id FROM category WHERE name = '바지'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('스니커즈 E', 9900, (SELECT id FROM brand WHERE name = 'E'), (SELECT id FROM category WHERE name = '스니커즈'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('가방 E', 2300, (SELECT id FROM brand WHERE name = 'E'), (SELECT id FROM category WHERE name = '가방'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('모자 E', 1800, (SELECT id FROM brand WHERE name = 'E'), (SELECT id FROM category WHERE name = '모자'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('양말 E', 2100, (SELECT id FROM brand WHERE name = 'E'), (SELECT id FROM category WHERE name = '양말'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('액세서리 E', 2100, (SELECT id FROM brand WHERE name = 'E'), (SELECT id FROM category WHERE name = '액세서리'), 'ON_SALE', NOW(), 'system', NOW(), 'system');
INSERT INTO product (name, price, brand_id, category_id, status, created_date, created_by, modified_date, modified_by) VALUES ('상의 F', 11200, (SELECT id FROM brand WHERE name = 'F'), (SELECT id FROM category WHERE name = '상의'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('아우터 F', 7200, (SELECT id FROM brand WHERE name = 'F'), (SELECT id FROM category WHERE name = '아우터'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('바지 F', 4000, (SELECT id FROM brand WHERE name = 'F'), (SELECT id FROM category WHERE name = '바지'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('스니커즈 F', 9300, (SELECT id FROM brand WHERE name = 'F'), (SELECT id FROM category WHERE name = '스니커즈'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('가방 F', 2100, (SELECT id FROM brand WHERE name = 'F'), (SELECT id FROM category WHERE name = '가방'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('모자 F', 1600, (SELECT id FROM brand WHERE name = 'F'), (SELECT id FROM category WHERE name = '모자'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('양말 F', 2300, (SELECT id FROM brand WHERE name = 'F'), (SELECT id FROM category WHERE name = '양말'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('액세서리 F', 1900, (SELECT id FROM brand WHERE name = 'F'), (SELECT id FROM category WHERE name = '액세서리'), 'ON_SALE', NOW(), 'system', NOW(), 'system');
INSERT INTO product (name, price, brand_id, category_id, status, created_date, created_by, modified_date, modified_by) VALUES ('상의 G', 10500, (SELECT id FROM brand WHERE name = 'G'), (SELECT id FROM category WHERE name = '상의'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('아우터 G', 5800, (SELECT id FROM brand WHERE name = 'G'), (SELECT id FROM category WHERE name = '아우터'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('바지 G', 3900, (SELECT id FROM brand WHERE name = 'G'), (SELECT id FROM category WHERE name = '바지'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('스니커즈 G', 9000, (SELECT id FROM brand WHERE name = 'G'), (SELECT id FROM category WHERE name = '스니커즈'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('가방 G', 2200, (SELECT id FROM brand WHERE name = 'G'), (SELECT id FROM category WHERE name = '가방'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('모자 G', 1700, (SELECT id FROM brand WHERE name = 'G'), (SELECT id FROM category WHERE name = '모자'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('양말 G', 2100, (SELECT id FROM brand WHERE name = 'G'), (SELECT id FROM category WHERE name = '양말'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('액세서리 G', 2000, (SELECT id FROM brand WHERE name = 'G'), (SELECT id FROM category WHERE name = '액세서리'), 'ON_SALE', NOW(), 'system', NOW(), 'system');
INSERT INTO product (name, price, brand_id, category_id, status, created_date, created_by, modified_date, modified_by) VALUES ('상의 H', 10800, (SELECT id FROM brand WHERE name = 'H'), (SELECT id FROM category WHERE name = '상의'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('아우터 H', 6300, (SELECT id FROM brand WHERE name = 'H'), (SELECT id FROM category WHERE name = '아우터'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('바지 H', 3100, (SELECT id FROM brand WHERE name = 'H'), (SELECT id FROM category WHERE name = '바지'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('스니커즈 H', 9700, (SELECT id FROM brand WHERE name = 'H'), (SELECT id FROM category WHERE name = '스니커즈'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('가방 H', 2100, (SELECT id FROM brand WHERE name = 'H'), (SELECT id FROM category WHERE name = '가방'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('모자 H', 1600, (SELECT id FROM brand WHERE name = 'H'), (SELECT id FROM category WHERE name = '모자'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('양말 H', 2000, (SELECT id FROM brand WHERE name = 'H'), (SELECT id FROM category WHERE name = '양말'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('액세서리 H', 2000, (SELECT id FROM brand WHERE name = 'H'), (SELECT id FROM category WHERE name = '액세서리'), 'ON_SALE', NOW(), 'system', NOW(), 'system');
INSERT INTO product (name, price, brand_id, category_id, status, created_date, created_by, modified_date, modified_by) VALUES ('상의 I', 11400, (SELECT id FROM brand WHERE name = 'I'), (SELECT id FROM category WHERE name = '상의'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('아우터 I', 6700, (SELECT id FROM brand WHERE name = 'I'), (SELECT id FROM category WHERE name = '아우터'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('바지 I', 3200, (SELECT id FROM brand WHERE name = 'I'), (SELECT id FROM category WHERE name = '바지'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('스니커즈 I', 9500, (SELECT id FROM brand WHERE name = 'I'), (SELECT id FROM category WHERE name = '스니커즈'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('가방 I', 2400, (SELECT id FROM brand WHERE name = 'I'), (SELECT id FROM category WHERE name = '가방'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('모자 I', 1700, (SELECT id FROM brand WHERE name = 'I'), (SELECT id FROM category WHERE name = '모자'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('양말 I', 1700, (SELECT id FROM brand WHERE name = 'I'), (SELECT id FROM category WHERE name = '양말'), 'ON_SALE', NOW(), 'system', NOW(), 'system'), ('액세서리 I', 2400, (SELECT id FROM brand WHERE name = 'I'), (SELECT id FROM category WHERE name = '액세서리'), 'ON_SALE', NOW(), 'system', NOW(), 'system');


INSERT INTO category_aggregate_info (category_id, lowest_price, lowest_price_product_id, highest_price, highest_price_product_id, created_date, created_by, modified_date, modified_by) WITH RankedProducts AS (SELECT c.id AS category_id, p.id AS product_id, p.price, ROW_NUMBER() OVER (PARTITION BY c.id ORDER BY p.price ASC) AS low_rank, ROW_NUMBER() OVER (PARTITION BY c.id ORDER BY p.price DESC) AS high_rank FROM product p INNER JOIN category c ON c.id = p.category_id) SELECT rp.category_id, MIN(CASE WHEN rp.low_rank = 1 THEN rp.price END) AS lowest_price, MIN(CASE WHEN rp.low_rank = 1 THEN rp.product_id END) AS lowest_price_product_id, MAX(CASE WHEN rp.high_rank = 1 THEN rp.price END) AS highest_price, MAX(CASE WHEN rp.high_rank = 1 THEN rp.product_id END) AS highest_price_product_id, CURRENT_TIMESTAMP AS created_date, 'system' AS created_by, CURRENT_TIMESTAMP AS modified_date, 'system' AS modified_by FROM RankedProducts rp GROUP BY rp.category_id;


